// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type HistoryEvent struct {
	ID                   int32        `json:"id"`
	Object               string       `json:"object"`
	Alarmcategoryorder   int32        `json:"alarmcategoryorder"`
	Highestalarmcategory string       `json:"highestalarmcategory"`
	Ackmessage           string       `json:"ackmessage"`
	StartTime            time.Time    `json:"start_time"`
	EndTime              sql.NullTime `json:"end_time"`
}

type HistoryEventDetail struct {
	ID            int32     `json:"id"`
	EventID       int32     `json:"event_id"`
	Object        string    `json:"object"`
	Alarmcategory string    `json:"alarmcategory"`
	CreatedAt     time.Time `json:"created_at"`
}

type Rule struct {
	ID                 int32     `json:"id"`
	Object             string    `json:"object"`
	Alarmcategoryorder int32     `json:"alarmcategoryorder"`
	Alarmlogic         string    `json:"alarmlogic"`
	Triggervalue       string    `json:"triggervalue"`
	Alarmcategory      string    `json:"alarmcategory"`
	Alamrmessage       string    `json:"alamrmessage"`
	CreatedAt          time.Time `json:"created_at"`
}
