// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type History struct {
	ID            int32          `json:"id"`
	Eventid       sql.NullString `json:"eventid"`
	Object        string         `json:"object"`
	Alarmcategory string         `json:"alarmcategory"`
	Ackmessage    sql.NullString `json:"ackmessage"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Rule struct {
	ID                 int32     `json:"id"`
	Object             string    `json:"object"`
	Alarmcategoryorder int32     `json:"alarmcategoryorder"`
	Alarmlogic         string    `json:"alarmlogic"`
	Triggervalue       string    `json:"triggervalue"`
	Alarmcategory      string    `json:"alarmcategory"`
	Alamrmessage       string    `json:"alamrmessage"`
	CreatedAt          time.Time `json:"created_at"`
}
