version: "3.9"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: alarm
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: thomas
      MYSQL_PASSWORD: 123456
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  alarm:
    image: thomaswei/alarm
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_USER: thomas
      DB_PASSWORD: 123456
      DB_DB: alarm
    ports:
      - 55555:55555
    depends_on:
      mysql:
        condition: service_healthy
