// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/AlarmRules.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AlarmRules_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AlarmRules_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_AlarmRules_proto_rawDescGZIP(), []int{0}
}

type SQLresponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *SQLresponse) Reset() {
	*x = SQLresponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_AlarmRules_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SQLresponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLresponse) ProtoMessage() {}

func (x *SQLresponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_AlarmRules_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLresponse.ProtoReflect.Descriptor instead.
func (*SQLresponse) Descriptor() ([]byte, []int) {
	return file_proto_AlarmRules_proto_rawDescGZIP(), []int{1}
}

func (x *SQLresponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_proto_AlarmRules_proto protoreflect.FileDescriptor

var file_proto_AlarmRules_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x75, 0x6c,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x51, 0x4c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x47, 0x0a, 0x11, 0x41, 0x6c,
	0x61, 0x72, 0x6d, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12,
	0x32, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x52, 0x75, 0x6c, 0x65,
	0x73, 0x12, 0x0b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x51, 0x4c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_AlarmRules_proto_rawDescOnce sync.Once
	file_proto_AlarmRules_proto_rawDescData = file_proto_AlarmRules_proto_rawDesc
)

func file_proto_AlarmRules_proto_rawDescGZIP() []byte {
	file_proto_AlarmRules_proto_rawDescOnce.Do(func() {
		file_proto_AlarmRules_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_AlarmRules_proto_rawDescData)
	})
	return file_proto_AlarmRules_proto_rawDescData
}

var file_proto_AlarmRules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_AlarmRules_proto_goTypes = []interface{}{
	(*Empty)(nil),       // 0: main.Empty
	(*SQLresponse)(nil), // 1: main.SQLresponse
}
var file_proto_AlarmRules_proto_depIdxs = []int32{
	0, // 0: main.AlarmRulesManager.InitAlarmRules:input_type -> main.Empty
	1, // 1: main.AlarmRulesManager.InitAlarmRules:output_type -> main.SQLresponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_AlarmRules_proto_init() }
func file_proto_AlarmRules_proto_init() {
	if File_proto_AlarmRules_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_AlarmRules_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_AlarmRules_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SQLresponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_AlarmRules_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_AlarmRules_proto_goTypes,
		DependencyIndexes: file_proto_AlarmRules_proto_depIdxs,
		MessageInfos:      file_proto_AlarmRules_proto_msgTypes,
	}.Build()
	File_proto_AlarmRules_proto = out.File
	file_proto_AlarmRules_proto_rawDesc = nil
	file_proto_AlarmRules_proto_goTypes = nil
	file_proto_AlarmRules_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AlarmRulesManagerClient is the client API for AlarmRulesManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AlarmRulesManagerClient interface {
	InitAlarmRules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SQLresponse, error)
}

type alarmRulesManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewAlarmRulesManagerClient(cc grpc.ClientConnInterface) AlarmRulesManagerClient {
	return &alarmRulesManagerClient{cc}
}

func (c *alarmRulesManagerClient) InitAlarmRules(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SQLresponse, error) {
	out := new(SQLresponse)
	err := c.cc.Invoke(ctx, "/main.AlarmRulesManager/InitAlarmRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlarmRulesManagerServer is the server API for AlarmRulesManager service.
type AlarmRulesManagerServer interface {
	InitAlarmRules(context.Context, *Empty) (*SQLresponse, error)
}

// UnimplementedAlarmRulesManagerServer can be embedded to have forward compatible implementations.
type UnimplementedAlarmRulesManagerServer struct {
}

func (*UnimplementedAlarmRulesManagerServer) InitAlarmRules(context.Context, *Empty) (*SQLresponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAlarmRules not implemented")
}

func RegisterAlarmRulesManagerServer(s *grpc.Server, srv AlarmRulesManagerServer) {
	s.RegisterService(&_AlarmRulesManager_serviceDesc, srv)
}

func _AlarmRulesManager_InitAlarmRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmRulesManagerServer).InitAlarmRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.AlarmRulesManager/InitAlarmRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmRulesManagerServer).InitAlarmRules(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _AlarmRulesManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.AlarmRulesManager",
	HandlerType: (*AlarmRulesManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAlarmRules",
			Handler:    _AlarmRulesManager_InitAlarmRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/AlarmRules.proto",
}
